# Generated by Django 2.2.1 on 2019-06-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=14)),
                ('tax_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=2017)),
                ('tax_code', models.IntegerField(default=12345)),
                ('agency', models.IntegerField(default=10010000)),
                ('agency_name', models.CharField(default='COUNTY OF COOK', max_length=50)),
                ('agency_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('tax_code_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('assessment_district', models.CharField(default='Barrington', max_length=50)),
                ('taxing_body_count', models.IntegerField(default=0)),
                ('equalization_factor', models.DecimalField(decimal_places=3, default=2.0, max_digits=6)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cctaxes.PropAddress')),
            ],
        ),
    ]
