# Generated by Django 2.2.1 on 2019-06-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcode',
            old_name='pin',
            new_name='user_address',
        ),
    ]
