# Generated by Django 2.2.1 on 2019-06-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0002_auto_20190605_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcode',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cctaxes.PropAddress'),
        ),
    ]
