# Generated by Django 2.2.1 on 2019-06-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0004_auto_20190609_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='propaddress',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
