# Generated by Django 2.2.1 on 2019-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0005_propaddress_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcode',
            name='agency_type',
            field=models.CharField(default='County', max_length=50),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='category_etr',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
