# Generated by Django 2.2.1 on 2019-06-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctaxes', '0006_auto_20190610_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propaddress',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
